version: "3.8"

services:
  mongodb:
    build: ./mongodb
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  scrapy:
    build: ./scrapy
    restart: always
    depends_on:
      - mongodb
    ports: 6000:6000