version: "3.8"

services:

  mongodb:
    build: ./mongodb
    restart: always
    ports:
      - 27017:27017
    env_file:
      - mongodb/.env
    # volumes:
    #   - db:/data/db

  scrapy:
    build: ./scrapy
    restart: always
    depends_on:
      - mongodb