version: "3.8"

services:

  mongodb:
    build: ./mongodb
    # restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    # volumes:
    #   - db:/data/db

  scrapy:
    build: ./scrapy
    # restart: on-failure
    depends_on:
      - mongodb